language: go

go:
  - 1.9    # (CURRENT - 1)
  - master

notifications:
  email: false

before_script:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo
  - go get -u github.com/kisielk/errcheck

script:
  - test -z "$(gofmt -s -l ./..)"
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 20 ./..
  - golint -set_exit_status $(go list ./...)
  - errcheck -asserts -blank ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
